require 'active_support/all'
require 'scribbler/version'
require 'scribbler/configurator'
require 'scribbler/base'
require 'scribbler/includeables'
require 'scribbler/cli'
require 'scribbler/executable'
